# Planning groups to use in PoseJog, and their corresponding VFC controllers.
# The number of elements in `planning_groups` and `controllers` must match.
planning_groups: ['left_manipulator', 'right_manipulator']
controllers: ['left_vfc', 'right_vfc']
