<?xml version="1.0" encoding="utf-8" ?>
<package format="3">
  <name>franka_spine_behaviors</name>
  <version>10.1.0</version>
  <description>MoveIt Pro Behaviors for the Franka vertical spine.</description>

  <maintainer email="support@picknik.ai">MoveIt Pro Maintainer</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>moveit_pro_package</build_depend>

  <depend>geometry_msgs</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_pro_behavior_interface</depend>
  <depend>pluginlib</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>ament_cmake_ros</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
