# Planning groups to use in JointJog, and their corresponding JVC controllers.
# The number of elements in `planning_groups` and `controllers` must match.
planning_groups: ['left_manipulator_without_spine', 'right_manipulator_without_spine', 'spine']
controllers: ['left_jvc', 'right_jvc', 'spine_jvc']
